authnapp/urls.py
from django.urls import path

import authnapp.views as authnapp

app_name = "authnapp"

urlpatterns = [
    path("login/", authnapp.login, name="login"),
    path("logout/", authnapp.logout, name="logout"),
    path("register/", authnapp.register, name="register"),
    path("edit/", authnapp.edit, name="edit"),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

from .apps import BasketappConfig

app_name = BasketappConfig.name

urlpatterns = [
    path("", basketapp.basket, name="view"),
    path("add/<int:pk>/", basketapp.basket_add, name="add"),
    path("remove/<int:pk>)/", basketapp.basket_remove, name="remove"),
]

djangoshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", mainapp.main, name="main"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("contacts/", mainapp.contacts, name="contacts"),
    path("details/", mainapp.details, name="details"),
    path("auth/", include("authnapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = "mainapp"

urlpatterns = [
    path("", mainapp.products, name="index"),
    path("category/<int:pk>/", mainapp.products, name="category"),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=64, unique=True)
    description = models.TextField(verbose_name="описание", blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="имя продукта", max_length=128)
    image = models.ImageField(upload_to="products_images", blank=True)
    short_desc = models.CharField(verbose_name="краткое описание продукта", max_length=60, blank=True)
    description = models.TextField(verbose_name="описание продукта", blank=True)
    price = models.DecimalField(verbose_name="цена продукта", max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name="количество на складе", default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"


class Contact(models.Model):
    phone = models.CharField(max_length=50, verbose_name="номер телефона")
    email = models.EmailField(max_length=254, verbose_name="электронная почта")
    city = models.CharField(max_length=128, default="Москва", verbose_name="город")
    address = models.CharField(max_length=254, verbose_name="адресс")

    def __str__(self):
        return f"{self.pk} {self.email}"

mainapp/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from basketapp.models import Basket

from .models import Contact, Product, ProductCategory


def main(request):
    title = "Interior"

    products = Product.objects.all()[:4]

    content = {"title": title, "products": products, "media_url": settings.MEDIA_URL}
    return render(request, "mainapp/index.html", content)


def products(request, pk=None):
    title = "Interior Products"
    links_menu = ProductCategory.objects.all()
    
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        # or you can use this
        # _basket = request.user.basket.all()
        # print(f'basket / _basket: {len(_basket)} / {len(basket)}')
    
    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by("price")
            category = {"name": "все"}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by("price")
        content = {
            "title": title,
            "links_menu": links_menu,
            "category": category,
            "products": products,
            "media_url": settings.MEDIA_URL,
            "basket": basket,
        }
        return render(request, "mainapp/products_list.html", content)
    same_products = Product.objects.all()
    content = {
        "title": title,
        "links_menu": links_menu,
        "same_products": same_products,
        "media_url": settings.MEDIA_URL,
        "basket": basket,
    }
    if pk:
        print(f"User select category: {pk}")
    return render(request, "mainapp/products.html", content)


def contacts(request):
    title = "Interior Contacts"
    visit_date = timezone.now()
    locations = Contact.objects.all()
    content = {"title": title, "visit_date": visit_date, "locations": locations}
    return render(request, "mainapp/contacts.html", content)


def details(request):
    title = "Interior Product details"
    content = {"title": title}
    return render(request, "mainapp/details.html", content)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="main-menu clearfix">
    <li class="main-menu-list">
        <a href="{% url 'products:category' pk=0 %}"
            class="main-menu-link {% if request.resolver_match.kwargs.pk == 0 %}active{% endif %}">
            все
        </a>
    </li>
    {% for link in links_menu %}
    <li class="main-menu-list">
        <a href="{% url 'products:category' link.pk %}" class="main-menu-link {% if request.resolver_match.kwargs.pk == link.pk %}main-menu-link-active{% endif %}">
            {{ link.name }}
        </a>
    </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_menu.html
{% load static %}

<a href="{% url 'main' %}"><img src="{% static 'img/logo.svg' %}" alt="logo"></a>
<ul class="menu clearfix">
    <li class="menu-list">
        <a href="{% url 'main' %}" class="menu-link {% if request.resolver_match.url_name == 'main' %}menu-link-active{% endif %}">
            HOME
        </a>
    </li>
    <li class="menu-list">
        <a href="{% url 'products:index' %}" class="menu-link {% if request.resolver_match.namespace == 'products' %}menu-link-active{% endif %}">
            PRODUCTS
        </a>
    </li>
    <li class="menu-list"><a href="#" class="menu-link">HISTORY</a></li>
    <li class="menu-list"> 
        <a href="{% url 'details' %}" class="menu-link {% if request.resolver_match.url_name == 'details' %}menu-link-active{% endif %}">
            SHOWROOM
        </a>
    </li>
    <li class="menu-list">
        <a href="{% url 'contacts' %}" class="menu-link {% if request.resolver_match.url_name == 'contacts' %}menu-link-active{% endif %}">
            CONTACT
        </a>
    </li>
    {% if user.is_authenticated %}
    <li class="menu-list">
        <a href="{% url 'auth:edit' %}" class="menu-link">
            {{ user.first_name|default:'USER' }}
        </a>
    </li>
    {% endif %}
    <li class="menu-list">
        {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}" class="menu-link">EXIT</a>
        {% else %}
        <a href="{% url 'auth:login' %}" class="menu-link">LOGIN</a>
        {% endif %}
    </li>
    <li class="menu-list menu-basket">
        <a href="{% url 'basket:view' %}" class="basket">
                <span>
                    {% if basket %} {{ basket|length }} {% endif %}
                </span>
        </a>
    </li>
    <li class="menu-list"><a href="#" class="menu-link"><img src="{% static 'img/search.svg' %}" alt="search"></a></li>
</ul>