authnapp/urls.py
from django.urls import path

import authnapp.views as authnapp

app_name = "authnapp"

urlpatterns = [
    path("login/", authnapp.login, name="login"),
    path("logout/", authnapp.logout, name="logout"),
    path("register/", authnapp.register, name="register"),
    path("edit/", authnapp.edit, name="edit"),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

from .apps import BasketappConfig

app_name = BasketappConfig.name

urlpatterns = [
    path("", basketapp.basket, name="view"),
    path("add/<int:pk>/", basketapp.basket_add, name="add"),
    path("remove/<int:pk>)/", basketapp.basket_remove, name="remove"),
]

djangoshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", mainapp.main, name="main"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("contacts/", mainapp.contacts, name="contacts"),
    path("details/", mainapp.details, name="details"),
    path("auth/", include("authnapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = "mainapp"

urlpatterns = [
    path("", mainapp.products, name="index"),
    path("category/<int:pk>/", mainapp.products, name="category"),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=64, unique=True)
    description = models.TextField(verbose_name="описание", blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="имя продукта", max_length=128)
    image = models.ImageField(upload_to="products_images", blank=True)
    short_desc = models.CharField(verbose_name="краткое описание продукта", max_length=60, blank=True)
    description = models.TextField(verbose_name="описание продукта", blank=True)
    price = models.DecimalField(verbose_name="цена продукта", max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name="количество на складе", default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"


class Contact(models.Model):
    phone = models.CharField(max_length=50, verbose_name="номер телефона")
    email = models.EmailField(max_length=254, verbose_name="электронная почта")
    city = models.CharField(max_length=128, default="Москва", verbose_name="город")
    address = models.CharField(max_length=254, verbose_name="адресс")

    def __str__(self):
        return f"{self.pk} {self.email}"

mainapp/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from basketapp.models import Basket

from .models import Contact, Product, ProductCategory


def main(request):
    title = "Interior"

    products = Product.objects.all()[:4]

    content = {"title": title, "products": products, "media_url": settings.MEDIA_URL}
    return render(request, "mainapp/index.html", content)


def products(request, pk=None):
    title = "Interior Products"
    links_menu = ProductCategory.objects.all()
    
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        # or you can use this
        # _basket = request.user.basket.all()
        # print(f'basket / _basket: {len(_basket)} / {len(basket)}')
    
    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by("price")
            category = {"name": "все"}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by("price")
        content = {
            "title": title,
            "links_menu": links_menu,
            "category": category,
            "products": products,
            "media_url": settings.MEDIA_URL,
            "basket": basket,
        }
        return render(request, "mainapp/products_list.html", content)
    same_products = Product.objects.all()
    content = {
        "title": title,
        "links_menu": links_menu,
        "same_products": same_products,
        "media_url": settings.MEDIA_URL,
        "basket": basket,
    }
    if pk:
        print(f"User select category: {pk}")
    return render(request, "mainapp/products.html", content)


def contacts(request):
    title = "Interior Contacts"
    visit_date = timezone.now()
    locations = Contact.objects.all()
    content = {"title": title, "visit_date": visit_date, "locations": locations}
    return render(request, "mainapp/contacts.html", content)


def details(request):
    title = "Interior Product details"
    content = {"title": title}
    return render(request, "mainapp/details.html", content)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|capfirst }}
        {% endblock title %}
    </title>

    {% block css %}
    {% endblock css %}

    {% block js %}
    {% endblock js %}

</head>

<body>
    <div class="container">

        {% block menu %}
        {% endblock menu %}

        <div class="content">
        {% block content %}
        {% endblock content %}
        </div>


        {% block footer %}
        <div class="footer">
            <div class="footer-content-1">
                <h2 class="footer-tag">Contact Us</h2>
                <p class="links">132A Bridge Road Richmond VIC Australia.</p>
                <p class="links">Talk to us on 1300 132 info@interior.com</p>
            </div>
            <div class="footer-content-2">
                <h2 class="footer-tag">Useful Information</h2>
                <div class="footer-content-2-1">
                    <p class="links-2">Sales terms Customer care Delivery</p>
                </div>
                <div class="footer-content-2-2">
                    <p class="links-2">Architect accounts Careers <br>Exchanges & returns</p>
                </div>
            </div>
            <div class="footer-content-3">
                <h2 class="footer-tag">Let’s Stay in Touch!</h2>
                <p class="links-3">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                <input type="email" placeholder="Your email address" class="input-email">
                <input type="image" src="{% static 'img/send_img.png' %}" alt="send_img.png" class="email-button">
            </div>
            <div class="footer-info">
                <p class="copyright">© Copyright - INTERIOR 2016. All Rights Reserved.</p>
                <a href="#" class="social-links"><img src="{% static 'img/social-links.png' %}" alt="social-links.png"></a>
                <p class="copyright">Terms & Conditions / Privacy policy & Cookies</p>
            </div>
        </div>
        {% endblock footer %}
    </div>

</body>

</html>

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'style-contacts.css' %}">
{% endblock css %}

{% block menu %}
		<div class="header-padding-contacts">
			<div class="header header-contacts clearfix">
				{% include 'mainapp/includes/inc_menu.html' %}
			</div>
			<div class="header-contacts-text">
				<p>Today: {{ visit_date|date:"l, j F, Y" }}</p>
				<h2 class="header-contacts-h2">Contact Us</h2>
			</div>
		</div>
{% endblock menu %}

{% block content %}
		<div class="main">
			{% for location in locations %}
			<div class="contacts-block"><a href="#" class="location-icon"><img src="{% static 'img/contacts/location_icon.png' %}" alt="location-icon"></a>
				<h2 class="contacts-h2">{{ location.city }}</h2>
				<p class="name">Phone:</p>
				<p class="contacts-text">{{ location.phone }}</p>
				<p class="name">Email:</p>
				<p class="contacts-text">{{ location.email }}</p>
				<p class="name">Address:</p>
				<p class="contacts-text contacts-text-address">{{ location.address }}</p>
			</div>
			{% endfor %}
		</div>
{% endblock content %}

mainapp/templates/mainapp/details.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'style-product-details.css' %}">
{% endblock css %}

{% block menu %}
		<div class="header header-details clearfix">
			{% include 'mainapp/includes/inc_menu.html' %}
		</div>
{% endblock menu %}

{% block content %}
		<div class="main">
			<ul class="main-menu clearfix">
				<li class="main-menu-list"><a href="#" class="main-menu-link main-menu-link-active">ALL</a></li>
				<li class="main-menu-list"><a href="#" class="main-menu-link">HOME</a></li>
				<li class="main-menu-list"><a href="#" class="main-menu-link">OFFICE</a></li>
				<li class="main-menu-list"><a href="#" class="main-menu-link">FURNITURE</a></li>
				<li class="main-menu-list"><a href="#" class="main-menu-link">MODERN</a></li>
				<li class="main-menu-list"><a href="#" class="main-menu-link">CLASSIC</a></li>
			</ul>
			<div class="details-slider clearfix">
				<a href="#"><img src="{% static 'img/products-details/slider_1.jpg' %}"></a>
				<div class="details-pagination">
					<a href="#"><img src="{% static 'img/products-details/controll_1.jpg' %}"></a>
					<a href="#"><img src="{% static 'img/products-details/controll_2.jpg' %}"></a>
					<a href="#"><img src="{% static 'img/products-details/controll_3.jpg' %}"></a>	
				</div>
			</div>
			<div class="details-text clearfix">
				<h2 class="details-h2">Fishnet Chair</h2>
				<p class="details-hot-deal">Hot Deal</p>
				<p class="price"><span class="text-other">$</span> 36.7<span class="text-other">/sq</span></p>
				<a href="#" class="details-button">Order Us <img src="{% static 'img/products-details/arrow.svg' %}" class="details-arrow" alt="arrow.svg"></a>
				<p class="details-main-text">The majesty of Mountains - Ugmonk style.</p>
				<p class="details-main-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</p>
				<p class="details-main-text">et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> 
				<p class="details-main-text">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
			</div>
			<div class="clr">
			</div>
			<div class="trending-text">
				<h2 class="trending-title">Related Products</h2>
				<a href="#" class="explore">explore all <img src="{% static 'img/arrow.svg' %}" alt="arrow.svg"></a>
			</div>
			<div class="products">
				<a href="#" class="main-product"><img src="{% static 'img/products/product_1.jpg' %}" alt="product_1.jpg"></a>
				<a href="#" class="main-product main-product-2"><img src="{% static 'img/products/product_2.jpg' %}" alt="product_2.jpg"></a>
				<a href="#" class="main-product"><img src="{% static 'img/products/product_3.jpg' %}" alt="product_3.jpg"></a>
			</div>	
		</div>
{% endblock content %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;700&display=swap">
{% endblock css %}

{% block menu %}
		<div class="slider padding-site">
			<div class="header clearfix">
				{% include 'mainapp/includes/inc_menu.html' %}
			</div>
			<div class="slider-text">
				<p class="slider-trending">TRENDING</p>
				<h2 class="slider-h2">Fishnet Chair</h2>
				<p class="slider-content">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black</p>
				<a href="#" class="button">Order Us <img src="{% static 'img/arrow.svg' %}" alt="arrow.svg"></a>
			</div>
			<div class="pagination">
				<a href="#" class="circle"></a><a href="#" class="circle circle-active"></a><a href="#" class="circle"></a>
			</div>
		</div>
{% endblock menu %}

{% block content %}
		<div class="featured-product">
			<ul class="featured-menu">
				<li class="featured-list"><a href="#" class="featured-link featured-link-active">Featured</a></li>
				<li class="featured-list"><a href="#" class="featured-link">New</a></li>
			</ul>
			<a href="#" class="explore">EXPLORE ALL<img src="{% static 'img/arrow.svg' %}" alt="arrow.svg"></a>
		</div>
		<div class="tab-content">
			{% for product in products %}
			<div class="block">
				<a href="{{ product.image }}"><img src="{{ media_url }}{{ product.image }}" alt="{{ product.short_desc }}">
					<div class="text">
						<img src="{% static 'img/icon-hover.png' %}" alt="img">
						<h4>{{ product.name }}</h4>
						<p>Описание: {{ product.description }} </p>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
		<div class="promo-product">
			<div class="promo-content-1">
				<div class="promo-text">
					<p class="promo-content-tag">exclusive</p>
					<h2 class="promo-h2">Fishnet Chair</h2>
					<p class="promo-content-details">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</p>
					<a href="#" class="button">Order Us <img src="{% static 'img/arrow.svg' %}" alt="arrow.svg"></a>
				</div>
			</div>
			<div class="promo-content-2">
				<div class="promo-text">
					<p class="promo-content-tag">exclusive</p>
					<h2 class="promo-h2">Fishnet Chair</h2>
					<p class="promo-content-details">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</p>
					<a href="#" class="button">Order Us <img src="{% static 'img/arrow.svg' %}" alt="arrow.svg"></a>
				</div>
			</div>
		</div>	
		<div class="trending-text">
			<h2 class="trending-title">Trending Products</h2>
			<a href="#" class="explore">explore all <img src="{% static 'img/arrow.svg' %}" alt="arrow.svg"></a>
		</div>
		<div class="trending-products">
			<a href="#" class="trending-product"><img src="{% static 'img/trending-products/product_5.jpg' %}" alt="product-5"></a>
			<a href="#" class="trending-product trending-product-6"><img src="{% static 'img/trending-products/product_6.jpg' %}" alt="product-6"></a>
			<a href="#" class="trending-product"><img src="{% static 'img/trending-products/product_7.jpg' %}" alt="product-7"></a>
			<a href="#" class="trending-product"><img src="{% static 'img/trending-products/product_8.jpg' %}" alt="product-8"></a>
			<a href="#" class="trending-product trending-product-9"><img src="{% static 'img/trending-products/product_9.jpg' %}" alt="product-9"></a>
			<a href="#" class="trending-product"><img src="{% static 'img/trending-products/product_10.jpg' %}" alt="product-10"></a>
		</div>
		<div class="slider-hot-deals">
			<div class="slider-hot-deals-text">
				<p class="slider-hot_deal">Hot deal</p>
				<h2 class="slider-h2">Fishnet Chair</h2>
				<p class="slider-content">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black</p>
				<a href="#" class="button">Order Us <img src="{% static 'img/arrow.svg' %}" alt="arrow.svg"></a>
			</div>
			<div class="pagination">
				<a href="#" class="circle"></a><a href="#" class="circle circle-active"></a><a href="#" class="circle"></a>
			</div>
		</div>
		<div class="exclusive-product">
			<div class="ex-product-1 clearfix">
				<div class="ex-product-1-text">
					<p class="promo-content-tag">exclusive</p>
					<h2 class="promo-h2">Fishnet Chair</h2>
					<p class="ex-product-details">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</p>
					<a href="#" class="button">Order Us <img src="{% static 'img/arrow.svg' %}" alt="arrow.svg"></a>
				</div>
			</div>
			<div class="ex-product-other clearfix">
				<a href="#" class="ex-product"><img src="{% static 'img/ex-products/ex_product_2.jpg' %}" alt="ex_product_2.jpg"></a>
				<a href="#" class="ex-product"><img src="{% static 'img/ex-products/ex_product_3.jpg' %}" alt="ex_product_3.jpg"></a>
				<a href="#" class="ex-product"><img src="{% static 'img/ex-products/ex_product_4.jpg' %}" alt="ex_product_4.jpg"></a>
				<a href="#" class="ex-product"><img src="{% static 'img/ex-products/ex_product_5.jpg' %}" alt="ex_product_5.jpg"></a>
			</div>
		</div>
		<div class="mobile-app">
			<div class="mobile-content">
				<p class="mobile-tag">mobile app</p>
				<h2 class="mobile-name">Find. Follow. Favorite.</h2>
				<p class="mobile-details">Save your favorites and share your style.</p>
				<a href="#" class="app-store"><img src="{% static 'img/mobile-app/app_store.jpg' %}" alt="app_store.jpg"></a>
				<a href="#" class="google-play"><img src="{% static 'img/mobile-app/google_play.jpg' %}" alt="google_play.jpg"></a>
			</div>
		</div>
{% endblock content %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'style-products.css' %}">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;700&display=swap">
{% endblock css %}

{% block menu %}
		<div class="header-padding-products">
			<div class="header header-products clearfix">
				{% include 'mainapp/includes/inc_menu.html' %}
			</div>
			<div class="header-products-text">
				<h2 class="header-products-h2">Our Products Range</h2>
			</div>
		</div>
{% endblock menu %}

{% block content %}
		<div class="main">
			{% include 'mainapp/includes/inc_categories_menu.html' %}
			<div class="products">
				{% for product in same_products %}
				<div class="block">
					<a href="#"><img src="{{ media_url }}{{ product.image }}" alt="{{ product.short_desc }}">
						<div class="text">
							<img src="/static/img/icon-hover.png" alt="img">
							<h3>Категория:{{ product.category.name }}</h3>
							<h4>Название: {{ product.name }}</h4>
							<p>Описание: {{ product.description }} </p>
							<p>Цена: {{ product.price }} </p>
							<p>На складе: {{ product.quantity }} </p>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
			<div class="refresh-button">
				<a href="#"><img src="{% static 'img/products/products_refresh.png' %}" alt="products-refresh.png"></a>
			</div>
			<div class="promo-product">
				<div class="promo-content-1">
					<div class="promo-text">
						<p class="promo-content-tag">exclusive</p>
						<h2 class="promo-h2">Fishnet Chair</h2>
						<p class="promo-content-details">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</p>
						<a href="#" class="button">Order Us <img src="{% static 'img/arrow.svg' %}" alt="arrow.svg"></a>
					</div>
				</div>
				<div class="promo-content-2">
					<div class="promo-text">
						<p class="promo-content-tag">exclusive</p>
						<h2 class="promo-h2">Fishnet Chair</h2>
						<p class="promo-content-details">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</p>
						<a href="#" class="button">Order Us <img src="{% static 'img/arrow.svg' %}" alt="arrow.svg"></a>
					</div>
				</div>
			</div>
		</div>
{% endblock content %}

mainapp/templates/mainapp/products_list.html
{% extends "mainapp/products.html" %}
{% load staticfiles %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include "mainapp/includes/inc_categories_menu.html" %}
    </div>

    <div class="products_list">
        <div class="title clearfix">
            <h2>Категория: "{{ category.name|title }}"</h2>
        </div>
        <div class="category-products clearfix">
            {% for product in products %}
            <div class="block">
                {% if user.is_authenticated %}
                <a href="{% url 'basket:add' product.pk %}">
                    {% else %}
                    <a href="{% url 'auth:login' %}">
                        {% endif %}
                        <img src="{{ media_url }}{{ product.image }}" alt="{{ product.short_desc }}">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.description }} </p>
                        </div>
                    </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="clr"></div>

{% endblock %}